// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, log4js, logger, path, server;

  express = require('express');

  path = require('path');

  log4js = require('log4js');

  log4js.configure({
    appenders: [
      {
        type: 'console'
      }, {
        type: 'file',
        filename: 'access.log',
        maxLogSize: 1024 * 1024,
        category: 'normal'
      }
    ]
  });

  logger = log4js.getLogger('normal');

  logger.setLevel('INFO');

  app = express();

  server = (require('http')).createServer(app);

  app.use(log4js.connectLogger(logger, {
    level: log4js.levels.INFO
  }));

  app.set('views', path.join(__dirname, 'views'));

  app.engine('html', require('ejs').renderFile);

  app.use(express["static"](path.join(__dirname, 'public')));

  app.use(require('connect-assets')());

  app.get('/', function(req, res) {
    return res.render('home.html');
  });

  app.get('/m/add', function(req, res) {
    logger.info(req.query.content);
    return res.send({
      success: 'success'
    });
  });

  app.get('/u/register', function(req, res) {});

  app.post('/u/login', function(req, res) {
    logger.info(req.body.password);
    return res.send({
      success: 'success'
    });
  });

  app.get('/u/logout', function(req, res) {});

  server.listen(7878);

}).call(this);
