// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, path;

  express = require('express');

  path = require('path');

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('views engine', 'jade');

  app.get('/', function(req, res) {
    return res.render('index');
  });

  app.listen(8989);

}).call(this);
