// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, log4js, path, routes, settings;

  express = require('express');

  path = require('path');

  log4js = require('log4js');

  routes = require('./routes/routes');

  settings = require('./settings');

  app = express();

  app.configure(function() {
    app.set('views', path.join(__dirname, 'views'));
    app.engine('html', require('ejs').renderFile);
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser());
    app.use(express.session({
      secret: settings.cookieSecret,
      store: new MongoStore({
        db: settings.db
      })
    }));
    app.use(app.router);
    return app.use(express["static"](path.join(__dirname, 'public')));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  routes(app);

  app.listen(7979);

}).call(this);
