express = require 'express'
path = require 'path'
log4js = require 'log4js'
console.log 'xx'
console.log 'xx'
console.log 'xx'
console.log 'xx'
console.log 'xx'
console.log 'xx'
routes = require './routes/routes'
settings = require './settings'