// Generated by CoffeeScript 1.6.3
// (function() {
  var NewsCtrl, NewsDetailCtrl;

  angular.module('newst', []).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/new', {
        templateUrl: 'new/new-list.html',
        controller: NewsCtrl
      }).when('/new/:newid', {
        templateUrl: 'new/new-detail.html',
        controller: NewsDetailCtrl
      }).otherwise({
        redirectTo: '/new'
      });
    }
  ]);

  NewsCtrl = function($scope, $http) {
    return $http.get("data/t.json").success(function(data) {
      return $scope.news = data;
    });
  };

  NewsDetailCtrl = function($scope, $routeParams) {
    return $scope.id = $routeParams.newid;
  };

// }).call(this);
