// Generated by CoffeeScript 1.6.3
(function() {
  var $, BookCtrl, MusicCtrl, ProfileCtrl, TaskCtrl;

  $ = jQuery;

  angular.module('gtd', []).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'templates/task.html',
        controller: TaskCtrl,
        resolve: TaskCtrl.resolve
      }).when('/movie', {
        templateUrl: 'templates/movie.html',
        controller: BookCtrl
      }).when('/music', {
        templateUrl: 'templates/music.html',
        controller: MusicCtrl
      }).when('/profile', {
        templateUrl: 'templates/profile.html',
        controller: ProfileCtrl
      }).otherwise({
        redirectTo: '/'
      });
    }
  ]);

  TaskCtrl = function($scope) {};


TaskCtrl.resolve = {
  delay: function($q) {
    var delay = $q.defer(),
    load = function(){
        $.getScript('js-foundation/drag-drop.js',function(){
        delay.resolve();
        });
    };
    load();
    return delay.promise;
  }
}

  BookCtrl = function($scope) {};

  MusicCtrl = function($scope) {};

  ProfileCtrl = function($scope) {};

  $(function() {
    return console.log('gtd, start');
  });

}).call(this);
