// Generated by CoffeeScript 1.6.1
(function() {
  var $, activeItem, activeManager, curItem, dragManager, initManager, isMouseDown, itemCopy, mouseOffset, mousePosition;

  $ = jQuery;

  dragManager = [];

  curItem = null;

  itemCopy = null;

  isMouseDown = false;

  mouseOffset = null;

  mousePosition = null;

  activeManager = null;

  activeItem = null;

  initManager = function(obj) {
    return obj.children().map(function(o) {
      return dragManager.push(o);
    });
  };

  $(function() {
    console.log('start');
    return initManager($("dragContainer"));
  });

}).call(this);
