// Generated by CoffeeScript 1.6.3
(function() {
  var diff, square, sum, sum_, test_arr;

  sum = function(arr) {
    var x, y, _i, _len, _results;
    y = 0;
    _results = [];
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      x = arr[_i];
      _results.push(y += x);
    }
    return _results;
  };

  square = function(x) {
    return x * x;
  };

  sum_ = function(arr) {
    var x, y, _i, _len, _results;
    y = 0;
    _results = [];
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      x = arr[_i];
      _results.push(y += square(x));
    }
    return _results;
  };

  diff = function(arr) {
    return (square(sum(arr))) - (sum_(arr));
  };

  test_arr = [1, 2, 3];

  console.log(diff(test_arr));

}).call(this);
